micronaut:
    ssl:
        enabled: true
        keyStore:
            path: file:/etc/cozycast/${HTTPS_DOMAIN}/server.p12
            password: ${KEYSTORE_PASSWORD}
            type: PKCS12
        port: 443
